; Unofficial Snes9x Windows v1.39 config file.

[windows]
;  0 - IDLE_PRIORITY_CLASS             Specify this class for a process whose threads run only when
;                                      the system is idle. The threads of the process are preempted
;                                      by the threads of any process running in a higher priority
;                                      class. An example is a screen saver. The idle-priority class is
;                                      inherited by child processes.
;
;  1 - NORMAL_PRIORITY_CLASS(default)  Specify this class for a process with no special scheduling
;                                      needs.
;
;  2 - HIGH_PRIORITY_CLASS             Specify this class for a process that performs time-critical
;                                      tasks that must be executed immediately. The threads of the
;                                      process preempt the threads of normal or idle priority class
;                                      processes. An example is Windows Task List, which must
;                                      respond quickly when called by the user, regardless of the
;                                      load on the operating system. Use extreme care when using
;                                      the high-priority class, because a high-priority class
;                                      application can use nearly all available CPU time.
;
;  3 - REALTIME_PRIORITY_CLASS         Specify this class for a process that has the highest possible
;                                      priority. The threads of the process preempt the threads of all
;                                      other processes, including operating system processes
;                                      performing important tasks. For example, a real-time process
;                                      that executes for more than a very brief interval can cause disk
;                                      caches not to flush or cause the mouse to be unresponsive.
PriorityClass=1

;  0 - THREAD_PRIORITY_LOWEST          Indicates 2 points below normal priority for the
;                                      priority class.
;
;  1 - THREAD_PRIORITY_BELOW_NORMAL    Indicates 1 point below normal priority for the
;                                      priority class.
;
;  2 - THREAD_PRIORITY_NORMAL(default) Indicates normal priority for the priority class.
;
;  3 - THREAD_PRIORITY_ABOVE_NORMAL    Indicates 1 point above normal priority for the
;                                      priority class.
;
;  4 - THREAD_PRIORITY_HIGHEST         Indicates 2 points above normal priority for the
;                                      priority class.
;
;  5 - THREAD_PRIORITY_IDLE            Indicates a base priority level of 1 for
;                                      IDLE_PRIORITY_CLASS,
;                                      NORMAL_PRIORITY_CLASS, or
;                                      HIGH_PRIORITY_CLASS processes, and a base
;                                      priority level of 16 for
;                                      REALTIME_PRIORITY_CLASS processes.
;
;  6 - THREAD_PRIORITY_TIME_CRITICAL   Indicates a base priority level of 15 for
;                                      IDLE_PRIORITY_CLASS,
;                                      NORMAL_PRIORITY_CLASS, or
;                                      HIGH_PRIORITY_CLASS processes, and a base
;                                      priority level of 31 for
;                                      REALTIME_PRIORITY_CLASS processes.
ThreadPriority=2

[graphics]
;  Windowed or Fullscreen.
;  0 - Window mode(default)
;  1 - Fullscreen mode
Fullscreen=0

;  DoubleRendering (default: Normal)
;  Enable Double(x2) Rendering Mode, Hi-Res mode need this setting enable.
;  0 - Normal
;  1 - Double
DoubleRendering=1

;  FullscreenDisplayModeIndex
;  0 -   256x224, 8bit
;  1 -   256x224,16bit
;  2 -   256x240, 8bit
;  3 -   256x240,16bit
;  4 -   320x240, 8bit
;  5 -   320x240,16bit
;  6 -   400x300, 8bit
;  7 -   400x300,16bit
;  8 -   512x384, 8bit
;  9 -   512x384,16bit
; 10 -   640x400, 8bit
; 11 -   640x400,16bit
; 12 -   512x448, 8bit
; 13 -   512x448,16bit
; 14 -   512x478, 8bit
; 15 -   512x478,16bit
; 16 -   640x480, 8bit
; 17 -   640x480,16bit
; 18 -   800x600, 8bit
; 19 -   800x600,16bit
; 20 -  1024x768, 8bit
; 21 -  1024x768,16bit
; 22 -  1152x864, 8bit
; 23 -  1152x864,16bit
; 24 - 1280x1024, 8bit
; 25 - 1280x1024,16bit
; 26 - 1600x1200, 8bit
; 27 - 1600x1200,16bit
;
;  16bit Normal Index 0-27 (default: 5)
FullscreenDisplayModeIndexNormal16=5
;
;  16bit Double Index 12-27 (default: 17)
FullscreenDisplayModeIndexDouble16=17
;
;   8bit Normal Index 0-27 (default: 4)
FullscreenDisplayModeIndexNormal8=4
;
;   8bit Double Index 12-27 (default: 16)
FullscreenDisplayModeIndexDouble8=16

;  DoubleRenderingModes16
;  Selection Double Rendering Modes to SixteenBit.
;  1 - HardwareX2(default)
;  2 - SoftwareX2
;  3 - Fake TV
;  4 - SuperEagle
;  5 - 2xSaI
;  6 - Super2xSaI
;  7 - Scale2xSaI
;  8 - TV Mode
DoubleRenderingModes16=1

;  DoubleRenderingModes8
;  Double Rendering Modes to 8bit.
;  1 - HardwareX2(default)
;  2 - SoftwareX2
;  3 - Fake TV
DoubleRenderingModes8=1

;  RenderingAsmMMX
;  0 - off
;  1 - on
RenderingAsmMMX=1

;  Enable direct Rendering to screen VRAM,
;  do speed up(raise frame rate) in several rendering mode.
;  0 - Disable
;  1 - Enable
DirectScreenRendering=0

;  DisableHardwareScale
;  0 - off(default)
;  1 - on
DisableHardwareScale=0

;  DoubleBuffering
;  Use DoubleBuffering on Fullscreen Mode(default: off)
;  0 - off
;  1 - on
DoubleBuffering=0

;  Windowed DirectDraw Clipper
;  Force Windowed DirectDraw Clipper or auto switch
;  Forced setting always do exactly DirectDraw cliping in window mode, but slowdown.
;  0 - Auto switch(default)
;  1 - Force
ForceWindowedDirectDrawClipper=0

;  OffScreenVRAM
;  This setting reserve offscreen buffer in VRAM area,
;  to Speed Up or Slow Down ???
;  default setting reserve system memory.
;  0 - off(default)
;  1 - on
OffScreenVRAM=0

;  BackBufferVRAM
;  0 - off(default)
;  1 - on
BackBufferVRAM=0

;  Use customized GFX engine.
;  0 - Disable(default)
;  1 - Enable
GFXengine2=1

;  Render SixteenBit (default: on)
;  0 - off
;  1 - on
RenderSixteenBit=1

;  Transparency (default: on)
;  0 - off
;  1 - on
Transparency=1

;  Swap background layer priorities from background involved in sub-screen
;  addition/subtraction. (default: disabled)
;  0 - Disable
;  1 - Enable
BGLayering=0

;  Disable graphics windows emulation. (default: enabled)
;  0 - Enable
;  1 - Disable
DisableGraphicWindows=0

;  Turn off the H-DMA emulation. Pressing '0' during a game toggles H-DMA on
;  and off. (default: enabled)
;  0 - Enable
;  1 - Disable
DisableHDMA=0

;  Enables Vsync to smoothen animation. (slows down emulation though)
;  (default: off)
;  0 - off
;  1 - on
wait_for_vsync=0

;  Stretch the SNES display to fit the whole computer display. 
;  (default: off)
;  0 - off
;  1 - on
;  2 - ClipScale
stretch=0

;  Enables Hi-Res mode. Makes HiRes SNES games look correct
;  (default: on)
;  0 - off
;  1 - on
hires=1

;  Enables the mode 7 bi-linear filter code.
;  (default: off)
;  0 - off
;  1 - on
Mode7Interpolate=0

[sound]
;  Sound Output (default: on)
;  0 - off
;  1 - on
APUEnabled=1

;  Sound Mode Index
;  0 -  8000Hz,   mono,  8bit
;  1 - 11025Hz,   mono,  8bit
;  2 - 22050Hz,   mono,  8bit
;  3 - 32000Hz,   mono,  8bit
;  4 - 44100Hz,   mono,  8bit
;  5 - 48000Hz,   mono,  8bit
;  6 -  8000Hz,   mono, 16bit
;  7 - 11025Hz,   mono, 16bit
;  8 - 22050Hz,   mono, 16bit
;  9 - 32000Hz,   mono, 16bit
; 10 - 44100Hz,   mono, 16bit
; 11 - 48000Hz,   mono, 16bit
; 12 -  8000Hz, stereo,  8bit
; 13 - 11025Hz, stereo,  8bit
; 14 - 22050Hz, stereo,  8bit
; 15 - 32000Hz, stereo,  8bit
; 16 - 44100Hz, stereo,  8bit
; 17 - 48000Hz, stereo,  8bit
; 18 -  8000Hz, stereo, 16bit
; 19 - 11025Hz, stereo, 16bit
; 20 - 22050Hz, stereo, 16bit
; 21 - 32000Hz, stereo, 16bit(default)
; 22 - 44100Hz, stereo, 16bit
; 23 - 48000Hz, stereo, 16bit
SoundMode=21

;  InterpolatedSound 'smoothens' sound and has a low pass filter [bass] effect 
InterpolatedSound=1

;  Sound playback buffer length 1-7(1 << (SoundBufferLength - 1))*10ms. (default: 3)
SoundBufferLength=3

;  SoundMixInterval 1-999ms. (default: 10)
SoundMixInterval=10

;  Create global Sound buffer. (default: 1)
SoundGlobalFocus=1

;  Enable volume envelope height reading by the sound CPU. (default: enabled)
SoundEnvelopeHeightReading=1

;  Disable Sound echo and FIR filter effects. (default: enabled)
;  0 - Enable
;  1 - Disable
DisableSoundEcho=0

;  Disable emulation of the sound DSP master volume control.
;  (default: enabled)
;  0 - Enable
;  1 - Disable
DisableMasterVolume=0

;  Volume level 1-5. (default: 1)
VolumeLevel=2

;  Disable decompressed sound sample caching. (default: enabled)
;  0 - Enable
;  1 - Disable
DisableSampleCaching=0

;  Sample decoding method
;  0 - Snes9x
;  1 - Anti Resonance
;  2 - Anti Resonance+AsmFix (default)
;  3 - ZSNES
;  4 - ZSNES++
;  5 - UOsnes9x
SampleDecodingMethod=2

;  Turn off a couple of speed hacks. The hacks boost the speed of many ROMs
;  but cause problems in a few ROMs. (default: enabled)
;  0 - Enable
;  1 - Disable
Shutdown=0

;  Sound Skip Waiting Method. (DO NOT use if sound output is enabled)
;  (default: 0)
;  valid values: 0 - 3 
SoundSkipMethod=0

;  Turns on sound-sync code where sound data is generated in sync with the
;  emulation of the SNES sound CPU instructions. Slighty slower emulation speed
;  but helps reduce note and sound effects timing problems and one or two 
;  games actually require this mode, notably Williams Arcade Classics.
;  (default: Disable)
;  0 - Disable
;  1 - Method 1
;  2 - Method 2
SoundSync=0

;  Reverse stereo sound output. (default: Disable)
;  0 - Disable
;  1 - Enable
ReverseStereo=0

;  ZSNES like low sound frequency mode.
;  (default: Enable)
;  0 - Disable
;  1 - Enable
FixFrequency=1

[cpu]
;  Percentage of CPU cycles to execute per scan line, decrease value to
;  increase emulation frame rate. Most ROMs work with a value of 85 or above.
;  1-199 (default: 100)
CyclesPercentage=100

;  Internal value of CPU execution for NTSC game's
;  CPU vertical counter by CPU cycles has reached this and flush frame.
;  Original Snes9x's default is 262.
;  1-999 (default: 269)
MaxNtscVcounter=269

;  Internal value of CPU execution for PAL game's
;  CPU vertical counter by CPU cycles has reached this and flush frame.
;  Original Snes9x's default is 312.
;  1-999 (default: 320)
MaxPalVcounter=320

;  High value decrease APU executions, but it is possible that GAME don't work.
;  Old Snes9x's default is 14, New Snes9x's default is 21.
;  1-99 (default: 21)
APU_OneCycle=21

;  Disable IRQ.
;  (default: Enable)
;  0 - Enable
;  1 - Disable
DisableIRQ=0

[timer]
;  Set this value to deliberately fix the frame skip rate and disable auto-
;  speed regulation. (default: auto-adjust)
;  valid values: 0 - 9
;  Leave blank for auto-adjust
SkipFrames=

;  Max value of frame skip for auto-adjust.
;  valid values: 0 - 10 (default: 10)
AutoMaxSkipFrames=10

;  It skip this frame count in Turbo mode.
;  valid values: (slow) 0 - 15 (fast) (default: 15)
TurboSkipFrames=15

;  If auto-adjust frame skip option is in effect, then the emulator will
;  try to maintain a constant game and music speed locked to this value by
;  skipping the rendering of some frames or waiting until the required time
;  is reached. Increase the value to slow down games, decrease it to speed
;  up games.(Default: 16 for NTSC, 20 for PAL)
NTSCtiming=16
PALtiming=20

[ControllerOption]
;  Snes input device settings.
;  1 - Exist
;  0 - None
;  (default: SnesMouse 1, SnesSuperScope 1, SnesMultiPlayer5 1)
SnesMouse=1
SnesSuperScope=1
SnesMultiPlayer5=1

;  Default pluged input device.
;  0 - SnesMultiPlayer5
;  1 - SnesJoypad (default)
;  2 - SnesMouseSwapped
;  3 - SnesMouse
;  4 - SnesSuperScope
DefaultPlugedInputDevice=1

;  Scanning rate for input device status
;  valid values 1 / ? : (high)1, 2, 4, 8(low)
;  low value raise frame rate, but do difficult to control
;  Original Snes9x's default is 1, UOsnes9x's default is 4.
JoyReadRate=4

;  Set DirectInput or WinAPI.
;  0 - WinAPI (default)
;  1 - DirectInput
DirectInput=0

;  Don't edit.
JoyKeyMappedFunctionCode0=0
JoyKeyMappedFunctionCode1=589824
JoyKeyMappedFunctionCode2=1179648
JoyKeyMappedFunctionCode3=1310720

;  Don't edit this section.
[joypad1]
Enable=1
Right=39
Left=37
Down=40
Up=38
StartButton=78
SelectButton=66
LButton=81
RButton=87
XButton=83
YButton=90
AButton=67
BButton=88
Right_Turbo=0
Left_Turbo=0
Down_Turbo=0
Up_Turbo=0
StartButton_Turbo=0
SelectButton_Turbo=0
LButton_Turbo=0
RButton_Turbo=0
XButton_Turbo=0
YButton_Turbo=0
AButton_Turbo=0
BButton_Turbo=0

;  Don't edit this section.
[joypad2]
Enable=0
Right=32769
Left=32768
Down=32771
Up=32770
StartButton=75
SelectButton=73
LButton=32
RButton=13
XButton=65
YButton=32780
AButton=76
BButton=68
Right_Turbo=0
Left_Turbo=0
Down_Turbo=0
Up_Turbo=0
StartButton_Turbo=0
SelectButton_Turbo=0
LButton_Turbo=0
RButton_Turbo=0
XButton_Turbo=0
YButton_Turbo=0
AButton_Turbo=0
BButton_Turbo=0

;  Don't edit this section.
[joypad3]
Enable=0
Right=0
Left=0
Down=0
Up=0
StartButton=0
SelectButton=0
LButton=0
RButton=0
XButton=0
YButton=0
AButton=0
BButton=0
Right_Turbo=0
Left_Turbo=0
Down_Turbo=0
Up_Turbo=0
StartButton_Turbo=0
SelectButton_Turbo=0
LButton_Turbo=0
RButton_Turbo=0
XButton_Turbo=0
YButton_Turbo=0
AButton_Turbo=0
BButton_Turbo=0

;  Don't edit this section.
[joypad4]
Enable=0
Right=0
Left=0
Down=0
Up=0
StartButton=0
SelectButton=0
LButton=0
RButton=0
XButton=0
YButton=0
AButton=0
BButton=0
Right_Turbo=0
Left_Turbo=0
Down_Turbo=0
Up_Turbo=0
StartButton_Turbo=0
SelectButton_Turbo=0
LButton_Turbo=0
RButton_Turbo=0
XButton_Turbo=0
YButton_Turbo=0
AButton_Turbo=0
BButton_Turbo=0

;  Don't edit this section.
[joypad5]
Enable=0
Right=0
Left=0
Down=0
Up=0
StartButton=0
SelectButton=0
LButton=0
RButton=0
XButton=0
YButton=0
AButton=0
BButton=0
Right_Turbo=0
Left_Turbo=0
Down_Turbo=0
Up_Turbo=0
StartButton_Turbo=0
SelectButton_Turbo=0
LButton_Turbo=0
RButton_Turbo=0
XButton_Turbo=0
YButton_Turbo=0
AButton_Turbo=0
BButton_Turbo=0

[gui]
;Sets the search directory for ROM images.
LastROMFileName=D:\etc\etc\SFC\”MŒŒ“ÁUƒX‚ØƒŠƒIƒ“.zip

;Recent Games
RecentROMFileName1=D:\etc\etc\SFC\”MŒŒ“ÁUƒX‚ØƒŠƒIƒ“.zip
RecentROMFileName2=
RecentROMFileName3=
RecentROMFileName4=
RecentROMFileName5=
RecentROMFileName6=
RecentROMFileName7=
RecentROMFileName8=
RecentROMFileName9=
RecentROMFileNameA=

;  Directory to store SRAM State save files to.
;  (ex. C:\SNES9X\SNESNAPS)
SnapShotDirectory=D:\etc\etc\SFC\snesnaps

;  Screen image file save directory.
;  (ex. C:\SNES9X\SCREEN)
ScreenShotDirectory=D:\etc\etc\SFC\snesnaps

;  Dumped SPC file save directory.
;  (ex. C:\SNES9X\SPC)
SPCDumpDirectory=D:\etc\etc\SFC\snesnaps

;  Language US or JP, this setting is switchable in JP environment.
;  0 - US
;  1 - JP
Language=1

;Don't edit.
WindowRectLeft=37
WindowRectRight=557
WindowRectTop=26
WindowRectBottom=570

[screenshot]
;  SaveImagefileFormat
;  0 - bmp (default)
;  1 - pcx
;  2 - gif
;  3 - png
SaveImagefileFormat=0

;  Reduce the color of image file to 256.
ReduceTheColorTo256=0

;  Reduce the color of image file to 256(8bit), if it's within 256.
ReduceTheColorTo256IfWithin=1

ImagefileHiresStretch=1

RLEcompression256bitmap=0

[debug]
DisplayScreenBufferAll=0

AdditionalInformationOnFpsDisplay=0

DisableROMFixes=0

[option]
;  Enable cheat code
;  It load cheat data "*.CHT" file from SnapShotDirectory.
;  0 - Disable
;  1 - Enable
ApplyCheats=0

ShowFPS=0

MuteSound=0

;  Don't edit.
RevID=76

