[quarrel bomber]

;●ウインドウモードで表示
;　0：フルスクリーンモード、
;　1：ウインドウモードです。
WINDOW = 1

;●影の表示
;　0：影を表示しません。
;　1：影を表示します。
SHADOW = 1

;●血の表示
;　0：血を表示しません。
;　1：血を表示します。
BLOOD = 1

;●サウンドの設定
;　0：サウンドを使用しません。
;　1：サウンドを使用します。
SOUND = 0

;●FPS表示の設定
;　0：FPSを表示しません。
;　1：FPSを表示します。
FPS = 1

